routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', [App\Http\Controllers\WcmsController::class, 'index'])->name('index');
Route::get('/about-us', [App\Http\Controllers\WcmsController::class, 'about_us'])->name('about_us');
Route::get('/contact-us', [App\Http\Controllers\WcmsController::class, 'contact_us'])->name('contact_us');
Route::get('/our-services', [App\Http\Controllers\WcmsController::class, 'our_services'])->name('our_services');
Route::get('/our-tour', [App\Http\Controllers\WcmsController::class, 'our_tour'])->name('our_tour');
Route::get('/travel-form', [App\Http\Controllers\WcmsController::class, 'travel_form'])->name('travel_form');
Route::get('get_travel_form', [App\Http\Controllers\WcmsController::class, 'get_travel_form'])->name('get_travel_form');
Route::get('/get-quotes', [App\Http\Controllers\WcmsController::class, 'get_quotes'])->name('get_quotes');

Route::post('/contact_us_store', [App\Http\Controllers\WcmsController::class, 'contact_us_store'])->name('contact_us_store');
Route::post('/quotes_store', [App\Http\Controllers\WcmsController::class, 'quotes_store'])->name('quotes_store');
Route::post('/book_tour', [App\Http\Controllers\WcmsController::class, 'book_tour'])->name('book_tour');

Route::get('post/{id}/{slug}', [App\Http\Controllers\BlogController::class, 'single_post'])->name('single_post');
Route::get('posts_by_category', [App\Http\Controllers\BlogController::class, 'posts_by_category'])->name('posts_by_category');
Route::get('all_post/{cate_id?}', [App\Http\Controllers\BlogController::class, 'all_posts'])->name('all_post');
Route::post('comment_store', [App\Http\Controllers\BlogController::class, 'comment_store'])->name('comment.store');



Route::group( [ 'middleware' => 'auth' , 'prefix' => 'admin','as' => 'admin.'], function(){

    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class, 'index'])->name('dashboard');
   
    Route::get('/about_us', [App\Http\Controllers\Admin\AdminController::class, 'about_us'])->name('about_us');
    Route::get('/contact_us', [App\Http\Controllers\Admin\AdminController::class, 'contact_us'])->name('contact_us');
    Route::get('/our_services', [App\Http\Controllers\Admin\AdminController::class, 'our_services'])->name('our_services');
    Route::get('/our_tour', [App\Http\Controllers\Admin\AdminController::class, 'our_tour'])->name('our_tour');
    Route::get('/get_quotes', [App\Http\Controllers\Admin\AdminController::class, 'get_quotes'])->name('get_quotes');
    Route::get('/travel_form', [App\Http\Controllers\Admin\AdminController::class, 'travel_form'])->name('travel_form');
    Route::post('/store_travel_form', [App\Http\Controllers\Admin\AdminController::class, 'store_travel_form'])->name('store_travel_form');

    Route::post('/slider_images_upload', [App\Http\Controllers\Admin\PageController::class, 'slider_images_upload'])->name('slider_images_upload');
    Route::post('/delete_slider_image', [App\Http\Controllers\Admin\PageController::class, 'delete_slider_image'])->name('delete_slider_image');
    Route::post('/home_store', [App\Http\Controllers\Admin\PageController::class, 'home_store'])->name('home_store');
    Route::post('/about_us_store', [App\Http\Controllers\Admin\PageController::class, 'about_us_store'])->name('about_us_store');
    Route::post('/contact_us_store', [App\Http\Controllers\Admin\PageController::class, 'contact_us_store'])->name('contact_us_store');
    Route::post('/our_services_store', [App\Http\Controllers\Admin\PageController::class, 'our_services_store'])->name('our_services_store');
    Route::post('/our_tour_store', [App\Http\Controllers\Admin\PageController::class, 'our_tour_store'])->name('our_tour_store');

    Route::post('/cat_popup', [App\Http\Controllers\CategoryController::class, 'cat_popup'])->name('cat_popup');
    Route::post('/tag_popup', [App\Http\Controllers\TagController::class, 'tag_popup'])->name('tag_popup');
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    
    Route::get('ApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'ApproveComment'])->name('ApproveComment');
    Route::get('DisApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DisApproveComment'])->name('DisApproveComment');
    Route::get('DelApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DelApproveComment'])->name('DelApproveComment');
    Route::resource('comments', CommentController::class);

});
Auth::routes();

resources/views/layout/admin_app.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>WCMS Admin Panel</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{{asset('admin/style.css')}}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
      table.dataTable tr.odd{
        background-color: unset !important;
      }
      table.dataTable tr.even{
        background-color: unset !important;
      }
      table.dataTable tr.odd td.sorting_1{
        background-color: unset !important;
      }
      .fade:not(.show) {
        opacity: 1;
      }
      .modal{
        margin-top: 50px;
      }
      .modal-header{
        padding-top: 32px;
      }
      table.dataTable tr.even td.sorting_1{
        background-color: unset !important;
      }
    </style>
</head>

<body>
    <!-- Main Header -->
    @include('layout.admin_sidebar')

  
    <!-- Content Wrapper. Contains page content -->
    
    @yield('content')
      

    <!-- Main Footer -->
   
    <script>
        $(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
            });
        });
    </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
   

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

</body>
</html>

resources/views/layout/admin_sidebar.blade.php
  <!-- WCMS Vertical navbar -->
  <div class="vertical-nav bg-white" id="sidebar" style="overflow: auto">
    <div class="py-4 px-3 mb-4 bg-light">
      <div class="media d-flex align-items-center">
        <div class="media-body">
          <h4 class="m-0">Wcms Admin Panel</h4>
          <p class="font-weight-normal text-muted mb-0">bc180200194</p>
        </div>
      </div>
    </div>

    <p class="text-gray font-weight-bold text-uppercase px-3 small pb-4 mb-0">Dashboard</p>

    <ul class="nav flex-column bg-white mb-0">
      <li class="nav-item">
        <a href="{{route('admin.dashboard')}}" class="nav-link text-dark bg-light">
          <i class="fa fa-th-large mr-3 text-primary fa-fw"></i>
          Home
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.about_us')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          About Us
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.contact_us')}}" class="nav-link text-dark">
          <i class="fa fa-cubes mr-3 text-primary fa-fw"></i>
          Contact Us
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.get_quotes')}}" class="nav-link text-dark">
          <i class="fa fa-bell-o mr-3 text-primary fa-fw"></i>
          Get Quotes
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.our_services')}}" class="nav-link text-dark">
          <i class="fa fa-globe mr-3 text-primary fa-fw"></i>
          Our Services
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.our_tour')}}" class="nav-link text-dark">
          <i class="fa fa-address-book-o  mr-3 text-primary fa-fw"></i>
          Tours
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.travel_form')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          Travel Form
        </a>
      </li>

      <li class="nav-item">
        <a href="{{route('admin.category.create')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          Add Category
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.category.index')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          View Categories
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.tag.create')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          Add Tag
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.tag.index')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          View Tags
        </a>
      </li>

      <li class="nav-item">
        <a href="{{route('admin.post.create')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          Add Post
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.post.index')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          View Posts
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('admin.comments.index')}}" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          Comments
        </a>
      </li>
     

    
    
      
    
    
    
      <li class="nav-item">
        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();" class="nav-link text-dark">
          <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
          Logout
        </a>
        <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
          {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </div>
  <!-- End WCMS vertical navbar -->

resources/views/layout/app.blade.php
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{{asset('stylesheet/style.css')}}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <title>WCMS Home Page</title>
</head>


<body>
    <!-- Main Header -->
    @include('layout.header')

  
    <!-- Content Wrapper. Contains page content -->
    
    @yield('content')
      

    <!-- Main Footer -->
    @include('layout.footer')

    

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

</body>
</html>

resources/views/layout/footer.blade.php
<footer id="sticky-footer" class="bg-dark text-white p-3">
    <div class="container text-center">
      <small>Copyright &copy; VU MYTRAVLER</small>
    </div>
  </footer>

resources/views/layout/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
    <a class="navbar-brand" href="#">VU MyTravler</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link home-button-border" href="{{route('index')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('about_us')}}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('our_tour')}}">Our Tours</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('travel_form')}}">Book Tour</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('our_services')}}">Our Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('get_quotes')}}">Get Quotes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('all_post')}}">Blogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('contact_us')}}">Contact Us</a>
        </li>
      </ul>
    </div>
  </nav>
<!-- /.navbar -->