routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', [App\Http\Controllers\WcmsController::class, 'index'])->name('index');
Route::get('/about-us', [App\Http\Controllers\WcmsController::class, 'about_us'])->name('about_us');
Route::get('/contact-us', [App\Http\Controllers\WcmsController::class, 'contact_us'])->name('contact_us');
Route::get('/our-services', [App\Http\Controllers\WcmsController::class, 'our_services'])->name('our_services');
Route::get('/our-tour', [App\Http\Controllers\WcmsController::class, 'our_tour'])->name('our_tour');
Route::get('/travel-form', [App\Http\Controllers\WcmsController::class, 'travel_form'])->name('travel_form');
Route::get('get_travel_form', [App\Http\Controllers\WcmsController::class, 'get_travel_form'])->name('get_travel_form');
Route::get('/get-quotes', [App\Http\Controllers\WcmsController::class, 'get_quotes'])->name('get_quotes');

Route::post('/contact_us_store', [App\Http\Controllers\WcmsController::class, 'contact_us_store'])->name('contact_us_store');
Route::post('/quotes_store', [App\Http\Controllers\WcmsController::class, 'quotes_store'])->name('quotes_store');
Route::post('/book_tour', [App\Http\Controllers\WcmsController::class, 'book_tour'])->name('book_tour');

Route::get('post/{id}/{slug}', [App\Http\Controllers\BlogController::class, 'single_post'])->name('single_post');
Route::get('posts_by_category', [App\Http\Controllers\BlogController::class, 'posts_by_category'])->name('posts_by_category');
Route::get('all_post/{cate_id?}', [App\Http\Controllers\BlogController::class, 'all_posts'])->name('all_post');
Route::post('comment_store', [App\Http\Controllers\BlogController::class, 'comment_store'])->name('comment.store');



Route::group( [ 'middleware' => 'auth' , 'prefix' => 'admin','as' => 'admin.'], function(){

    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class, 'index'])->name('dashboard');
   
    Route::get('/about_us', [App\Http\Controllers\Admin\AdminController::class, 'about_us'])->name('about_us');
    Route::get('/contact_us', [App\Http\Controllers\Admin\AdminController::class, 'contact_us'])->name('contact_us');
    Route::get('/our_services', [App\Http\Controllers\Admin\AdminController::class, 'our_services'])->name('our_services');
    Route::get('/our_tour', [App\Http\Controllers\Admin\AdminController::class, 'our_tour'])->name('our_tour');
    Route::get('/get_quotes', [App\Http\Controllers\Admin\AdminController::class, 'get_quotes'])->name('get_quotes');
    Route::get('/travel_form', [App\Http\Controllers\Admin\AdminController::class, 'travel_form'])->name('travel_form');
    Route::post('/store_travel_form', [App\Http\Controllers\Admin\AdminController::class, 'store_travel_form'])->name('store_travel_form');

    Route::post('/slider_images_upload', [App\Http\Controllers\Admin\PageController::class, 'slider_images_upload'])->name('slider_images_upload');
    Route::post('/delete_slider_image', [App\Http\Controllers\Admin\PageController::class, 'delete_slider_image'])->name('delete_slider_image');
    Route::post('/home_store', [App\Http\Controllers\Admin\PageController::class, 'home_store'])->name('home_store');
    Route::post('/about_us_store', [App\Http\Controllers\Admin\PageController::class, 'about_us_store'])->name('about_us_store');
    Route::post('/contact_us_store', [App\Http\Controllers\Admin\PageController::class, 'contact_us_store'])->name('contact_us_store');
    Route::post('/our_services_store', [App\Http\Controllers\Admin\PageController::class, 'our_services_store'])->name('our_services_store');
    Route::post('/our_tour_store', [App\Http\Controllers\Admin\PageController::class, 'our_tour_store'])->name('our_tour_store');

    Route::post('/cat_popup', [App\Http\Controllers\CategoryController::class, 'cat_popup'])->name('cat_popup');
    Route::post('/tag_popup', [App\Http\Controllers\TagController::class, 'tag_popup'])->name('tag_popup');
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    
    Route::get('ApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'ApproveComment'])->name('ApproveComment');
    Route::get('DisApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DisApproveComment'])->name('DisApproveComment');
    Route::get('DelApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DelApproveComment'])->name('DelApproveComment');
    Route::resource('comments', CommentController::class);

});
Auth::routes();

resources/views/admin/about_us.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->

<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a target="_blank" style="float: right;" href="{{route('about_us')}}" class="btn btn-light">View</a>
    <!-- WCMS content -->
    <form action="{{route('admin.about_us_store')}}" method="POST" enctype="multipart/form-data">
      @csrf
    <h2 class="display-3 text-white">WMCS About Us</h2>
    <div class="separator"></div>
    <div class="form-group">
        <h2 class="mb-3 text-white">About us Text</h2>
        <textarea class="form-control" id="about_us_text" name="about_us_text" rows="3">{{$about_us_text}}</textarea>
      </div>
        <div class="form-group text-white">
            <!-- About Us Image-->
            <h2 class="mt-3">About Us Image</h2>
            <input type="file" class="form-control-file mb-5 mt-5" id="about_us_image" name="about_us_image">
            @if($about_us_image != '')
              <img src="{{ asset('about_us/'.$about_us_image.'')}}" class="sliderImages" style="width: 150px" />
            @endif
    </div>
    <button type="submit" class="mt-5 btn btn-light" style="width: 100%;">Save</button>
    </form>
</div>
@endsection

resources/views/admin/contact_us.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->
<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a target="_blank" style="float: right;" href="{{route('contact_us')}}" class="btn btn-light">View</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">WMCS Tours</h2>
    <div class="separator"></div>
<form action="{{route('admin.contact_us_store')}}" method="POST" enctype="multipart/form-data" class="mb-5">
      @csrf
<div class="row text-white mb-0">
    <div class="col-md-4">
        <h2>Contact Number</h2>
        <input class="form-control" type="text" placeholder="Enter Contact number" name="contact_number" id="contact_number" value="{{$contact_number}}">
    </div>
    <div class="col-md-4">
        <h2>Email Address</h2>
        <input class="form-control" type="text" placeholder="Enter Contact number" name="email_address" value="{{$email_address}}">
    </div>
    <div class="col-md-4">
        <h2>Address</h2>
        <input class="form-control" type="text" placeholder="Enter Contact number" name="address" value="{{$address}}">
    </div>
    <button type="submit" class="mt-5 btn btn-light" style="width: 100%;">Save</button>


</div>
</form>

<table class="table text-white" id="contact_table">
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">User First Name</th>
    <th scope="col">User Last Name</th>
    <th scope="col">User Email</th>
    <th scope="col">User Message</th>
  </tr>
</thead>
<tbody>
  @foreach ($contact_us_data as  $data)
  <tr>
    <th>{{$data->id}}</th>
    <td>{{$data->fname}}</td>
    <td>{{$data->lname}}</td>
    <td>{{$data->email}}</td>
    <td>{{$data->messaage}}</td>
  </tr>
  @endforeach
  
</tbody>
</table>

</div>

<script>
  $(document).ready( function () {
  $(function(){
    $("#contact_table").dataTable();
  });

  });
</script>
@endsection

resources/views/admin/get_quotes.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->

<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a target="_blank" style="float: right;" href="{{route('get_quotes')}}" class="btn btn-light">View</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">WMCS Subscribed Email List</h2>
    <table class="table text-white" id="quote_table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Emails</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($quotes as $quote)
            <tr>
                <th>{{$quote->id}}</th>
                <td>{{$quote->email}}</td>
            </tr>
            @endforeach
          
          
        </tbody>
        </table>
        
    <div class="separator"></div>

    

    </div>

    <script>
        $(document).ready( function () {
        $(function(){
          $("#quote_table").dataTable();
        });

        });
    </script>
@endsection

resources/views/admin/index.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->
<div class="page-content p-5" id="content">
    <!-- Toggle button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
        class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
        <a target="_blank" style="float: right;" href="{{route('index')}}" class="btn btn-light">View</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">WCMS Editor</h2>
    
    <div class="separator"></div>
<form action="{{route('admin.home_store')}}" method="POST" enctype="multipart/form-data">
  @csrf
  <div class="container-fluid">
    <div class="form-group  text-white">
      <!-- Select Carasoul Images-->  
      <h2 class="mt-3">Select Carasoul Images</h2>
      <input type="file" class="form-control-file mb-5 mt-5" id="slider_images" name="slider_images" accept="image/jpg, image/jpeg, image/gif, image/png" multiple>
  </div>
  <div class="row" id="sliderImages">
    @if(isset($slider_images))
    @foreach($slider_images as $key=>$value)
    <img src="{{ asset('home/slider_images/'.$value->image.'')}}" class="sliderImages" style="width: 150px" /> <a
        data-id="{{ $value->id }}" href="javascript:" class="delete_sliderImage">&times;</a>
    @endforeach
    @endif
  </div>
  <input type="hidden" id="uploadedImgId" name="uploadedImageIds">
</div>
    <!-- Why Choose us -->
    <div class="container-fluid text-white">
      <div class="form-group">
        <h2 class="mb-3">Why Choose Us</h2>
        <textarea class="form-control" id="why_choose_us" name="why_choose_us" rows="3">{{$why_choose_us}}</textarea>
      </div>
      <div class="form-group">
        <h2 class="mb-3">Why Choose Us(Image)</h2>
        <input type="file" class="form-control-file mb-5 mt-5" id="why_choose_us_image" name="why_choose_us_image">
        @if($why_choose_us_image != '')
        <img src="{{ asset('home/'.$why_choose_us_image.'')}}" class="sliderImages" style="width: 150px" />
        @endif
      </div>
    </div>
    <input type="submit" class="btn btn-light w-100" value="submit">
</form>
</div>

<script>

function imageDisplay() {
        if (window.File && window.FileReader && window.FileList && window.Blob) //check File API supported browser
        {

                var data = $('#slider_images')[0].files; //this file data

            $.each(data, function(index, file){ //loop though each file
            if(/(\.|\/)(gif|jpe?g|png)$/i.test(file.type)){ //check supported file type
            var fRead = new FileReader(); //new filereader
            fRead.onload = (function(file){ //trigger function on successful read
            return function(e) {
                let imageId = $('#uploadedImgId').val();
                var img = '';

                    img = '<img src="'+e.target.result+'" class="sliderImages" style="width: 150px" /> <a data-id="'+ imageId +'"href="javascript:" class="delete_sliderImage">&times;</a>' //create image element
                    $('#sliderImages').append(img); //append image to output element

                };
                })(file);
                fRead.readAsDataURL(file); //URL representing the file's data.
                }

                    $('#slider_images').val('');

                });
                }else{
                    swal("Error!", "Your browser doesn't support File API!", "error");
                    //if File API is absent
                    }
                }



                $(document).on('click','.delete_sliderImage',function(){
                    let imageId = $(this).data('id');
                    deleteImage(imageId);
                    $(this).prev('img').remove();
                    $(this).remove();
                });

                function deleteImage(imageId) {
                    var part_id = $('#part_id').val();
                    $.ajax({
                            type: "POST",
                            url: "{{route('admin.delete_slider_image')}}",
                            data: {'id': imageId,'_token': '{{ csrf_token() }}', 'part_id': part_id},
                            success: function(data) {
                                if(data['success'] == true) {

                                }
                            },
                            error: function() {
                                swal("Sorry!", "There is an error", "error");
                            }
                        });
                }
    $(document).ready( function () {
      $('#slider_images').on('change', function(){

    // if($('.uploadedRecImg').length == 4) {
    //     swal("Sorry!", "You can not upload more than four images", "error");
    //     return;
    // }
    var fd = new FormData();
    var token = "{{ csrf_token() }}";
    var files = $('#slider_images')[0].files;
    console.log(files[0]);
    fd.append('slider_image',files[0]);
    fd.append('_token',token);
    
    $.ajax({
            type: "POST",
            url: "{{ route('admin.slider_images_upload') }}",
            data: fd,
            dataType: "json",
            processData: false,
            contentType: false,
            success: function(data) {
                if(data['success'] == true) {
                    id = data['id'];
                    $('input[type="hidden"][name*="uploadedImageIds"]').val(id);
                    imageDisplay();
                }
            },
            error: function() {
                swal("Sorry!", "There is an error", "error");
            }
        });



    });

    });
</script>

@endsection

resources/views/admin/our_services.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->
<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a target="_blank" style="float: right;" href="{{route('our_services')}}" class="btn btn-light">View</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">WMCS Services</h2>
    <div class="separator"></div>
    <!-- Edit Content-->
    <form action="{{route('admin.our_services_store')}}" method="POST" enctype="multipart/form-data" class="mb-5">
        @csrf
    <div class="row mt-2 w-100 text-white">
        <div class="col-md-12">
            <div class="form-group">
                <h2 class="mb-3 text-white">Clean Room Text</h2>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="room">{{$room}}</textarea>
              </div>
        </div>
    </div>
    <div class="row mt-2 w-100 text-white">
        <div class="col-md-12">
            <div class="form-group">
                <h2 class="mb-3 text-white">Clean Night Buffet</h2>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="night_buffet">{{$night_buffet}}</textarea>
              </div>
        </div>
        <!-- End Edit Content-->
    </div>
    <div class="row mt-2 w-100 text-white">
        <div class="col-md-12">
            <div class="form-group">
                <h2 class="mb-3 text-white">Edit Cricket</h2>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="cricket">{{$cricket}}</textarea>
              </div>
        </div>
    </div>
    <div class="row mt-2 w-100 text-white">
        <div class="col-md-12">
            <div class="form-group">
                <h2 class="mb-3 text-white">Edit Destinations</h2>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="destination">{{$destination}}</textarea>
              </div>
        </div>
    </div>
    <div class="row mt-2 w-100 text-white">
        <div class="col-md-12">
            <div class="form-group">
                <h2 class="mb-3 text-white">Edit Food</h2>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="food">{{$food}}</textarea>
              </div>
        </div>
    </div>
    <div class="row mt-2 w-100 text-white">
        <div class="col-md-12">
            <div class="form-group">
                <h2 class="mb-3 text-white">Edit Bath</h2>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="bath">{{$bath}}</textarea>
              </div>
        </div>
        <button type="submit" class="mt-5 btn btn-light" style="width: 100%;">Save</button>

    </div>
    </form>
</div>
@endsection

resources/views/admin/our_tour.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->


    <div class="page-content p-5" id="content">
        <!-- Toggle Navbar button -->
        <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
                class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
                <a target="_blank" style="float: right;" href="{{route('our_tour')}}" class="btn btn-light">View</a>
        <!-- WCMS content -->
        <form action="{{route('admin.our_tour_store')}}" method="POST" enctype="multipart/form-data" class="mb-5">
          @csrf
        <h2 class="display-3 text-white">WMCS Tours</h2>
        <div class="separator"></div>
        <div class="form-group">
            <h2 class="mb-3 text-white">Tours Text 1</h2>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tour_1_text">{{$tour_1_text}}</textarea>
          </div>
            <div class="form-group text-white">
                <!-- About Us Image-->
                <h2 class="mt-3">Tours Image 1</h2>
                <input type="file" class="form-control-file mb-5 mt-5" id="exampleFormControlFile1" name="tour_1_image">
                @if($tour_1_image != '')
                  <img src="{{ asset('tour/'.$tour_1_image.'')}}" class="sliderImages" style="width: 150px" />
                @endif
        </div>
        <div class="form-group">
            <h2 class="mb-3 text-white">Tours Text 2</h2>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tour_2_text">{{$tour_2_text}}</textarea>
          </div>
            <div class="form-group text-white">
                <!-- About Us Image-->
                <h2 class="mt-3">Tours Image 2</h2>
                <input type="file" class="form-control-file mb-5 mt-5" id="exampleFormControlFile1"  name="tour_2_image">
                @if($tour_2_image != '')
                <img src="{{ asset('tour/'.$tour_2_image.'')}}" class="sliderImages" style="width: 150px" />
              @endif
              </div>
        <div class="form-group">
            <h2 class="mb-3 text-white">Tours Text 3</h2>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tour_3_text">{{$tour_3_text}}</textarea>
          </div>
            <div class="form-group text-white">
                <!-- About Us Image-->
                <h2 class="mt-3">Tours Image 3</h2>
                <input type="file" class="form-control-file mb-5 mt-5" id="exampleFormControlFile1"  name="tour_3_image">
                @if($tour_3_image != '')
                <img src="{{ asset('tour/'.$tour_3_image.'')}}" class="sliderImages" style="width: 150px" />
                @endif
              </div>
        <button type="submit" class="mt-5 btn btn-light" style="width: 100%;">Save</button>
        </form>
            </div>


@endsection

resources/views/admin/travel_form.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->

<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a target="_blank" style="float: right;" href="{{route('travel_form')}}" class="btn btn-light">View</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">WMCS Tours Applications</h2>
    <div class="separator"></div>
    <div id="fb-editor"></div>
    <h4 class="text-white">Existing Table</h4>
    <div class="mt-3 mb-5" id="render-wrap"></div>
    <h4 class="text-white">Data From Frontend</h4>
    <table class="table text-white table-bordered" id="bookings" >
        
        <tbody>
          @foreach ($bookings as  $data)
          <tr>
            <th scope="row">{{$data->id}}</th>
            @php
               $data = json_decode($data->tour_form_json,true);
               $i = 0; 
            @endphp
          @foreach($data as $key => $value)
            @if($key == '_token')
              @continue
            @endif
           <td>{{$value}}</td>  
          @endforeach 
          
          </tr>
          @endforeach
          
        </tbody>
      </table>
      
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
  <script src="https://formbuilder.online/assets/js/form-render.min.js"></script>
  <script>
    var options = {
      onSave: function(evt, formData) {
        
          console.log(formData);
        
          var url = "{{ route('admin.store_travel_form') }}";
          var token = "{{ csrf_token() }}";

                       $.ajax({
                           type: 'POST',
                               url: url,
                               data: {'_token': token, 'formData': formData},
                               success: function (response) {
                                 swal("Form Save Successfully");
                                 window.location.reload();

                           }
                       });
        },
    };
  $('#fb-editor').formBuilder(options);
  

  
</script>
<script>
  $(document).ready( function () {
  $(function(){
    $("#bookings").dataTable();
  });

  var url = "{{ route('get_travel_form') }}";
         
                       $.ajax({
                           type: 'GET',
                               url: url,
                               
                               success: function (response) {
                                /* console.log(typeof(response));
                                console.log(response);
                                $(".render-wrap").formRender({response}); */
                                const code = document.getElementById("render-wrap");
                                const formData = response;
                                const addLineBreaks = html => html.replace(new RegExp("><", "g"), ">\n<");

                                // Grab markup and escape it
                                const $markup = $("<div/>");
                                $markup.formRender({ formData });

                                // set < code > innerText with escaped markup
                                $("#render-wrap").html(addLineBreaks($markup.formRender("html")));

                           }
  });

  });
</script>
@endsection