routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', [App\Http\Controllers\WcmsController::class, 'index'])->name('index');
Route::get('/about-us', [App\Http\Controllers\WcmsController::class, 'about_us'])->name('about_us');
Route::get('/contact-us', [App\Http\Controllers\WcmsController::class, 'contact_us'])->name('contact_us');
Route::get('/our-services', [App\Http\Controllers\WcmsController::class, 'our_services'])->name('our_services');
Route::get('/our-tour', [App\Http\Controllers\WcmsController::class, 'our_tour'])->name('our_tour');
Route::get('/travel-form', [App\Http\Controllers\WcmsController::class, 'travel_form'])->name('travel_form');
Route::get('get_travel_form', [App\Http\Controllers\WcmsController::class, 'get_travel_form'])->name('get_travel_form');
Route::get('/get-quotes', [App\Http\Controllers\WcmsController::class, 'get_quotes'])->name('get_quotes');

Route::post('/contact_us_store', [App\Http\Controllers\WcmsController::class, 'contact_us_store'])->name('contact_us_store');
Route::post('/quotes_store', [App\Http\Controllers\WcmsController::class, 'quotes_store'])->name('quotes_store');
Route::post('/book_tour', [App\Http\Controllers\WcmsController::class, 'book_tour'])->name('book_tour');

Route::get('post/{id}/{slug}', [App\Http\Controllers\BlogController::class, 'single_post'])->name('single_post');
Route::get('posts_by_category', [App\Http\Controllers\BlogController::class, 'posts_by_category'])->name('posts_by_category');
Route::get('all_post/{cate_id?}', [App\Http\Controllers\BlogController::class, 'all_posts'])->name('all_post');
Route::post('comment_store', [App\Http\Controllers\BlogController::class, 'comment_store'])->name('comment.store');



Route::group( [ 'middleware' => 'auth' , 'prefix' => 'admin','as' => 'admin.'], function(){

    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class, 'index'])->name('dashboard');
   
    Route::get('/about_us', [App\Http\Controllers\Admin\AdminController::class, 'about_us'])->name('about_us');
    Route::get('/contact_us', [App\Http\Controllers\Admin\AdminController::class, 'contact_us'])->name('contact_us');
    Route::get('/our_services', [App\Http\Controllers\Admin\AdminController::class, 'our_services'])->name('our_services');
    Route::get('/our_tour', [App\Http\Controllers\Admin\AdminController::class, 'our_tour'])->name('our_tour');
    Route::get('/get_quotes', [App\Http\Controllers\Admin\AdminController::class, 'get_quotes'])->name('get_quotes');
    Route::get('/travel_form', [App\Http\Controllers\Admin\AdminController::class, 'travel_form'])->name('travel_form');
    Route::post('/store_travel_form', [App\Http\Controllers\Admin\AdminController::class, 'store_travel_form'])->name('store_travel_form');

    Route::post('/slider_images_upload', [App\Http\Controllers\Admin\PageController::class, 'slider_images_upload'])->name('slider_images_upload');
    Route::post('/delete_slider_image', [App\Http\Controllers\Admin\PageController::class, 'delete_slider_image'])->name('delete_slider_image');
    Route::post('/home_store', [App\Http\Controllers\Admin\PageController::class, 'home_store'])->name('home_store');
    Route::post('/about_us_store', [App\Http\Controllers\Admin\PageController::class, 'about_us_store'])->name('about_us_store');
    Route::post('/contact_us_store', [App\Http\Controllers\Admin\PageController::class, 'contact_us_store'])->name('contact_us_store');
    Route::post('/our_services_store', [App\Http\Controllers\Admin\PageController::class, 'our_services_store'])->name('our_services_store');
    Route::post('/our_tour_store', [App\Http\Controllers\Admin\PageController::class, 'our_tour_store'])->name('our_tour_store');

    Route::post('/cat_popup', [App\Http\Controllers\CategoryController::class, 'cat_popup'])->name('cat_popup');
    Route::post('/tag_popup', [App\Http\Controllers\TagController::class, 'tag_popup'])->name('tag_popup');
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    
    Route::get('ApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'ApproveComment'])->name('ApproveComment');
    Route::get('DisApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DisApproveComment'])->name('DisApproveComment');
    Route::get('DelApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DelApproveComment'])->name('DelApproveComment');
    Route::resource('comments', CommentController::class);

});
Auth::routes();

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public function Category()
  {
      return $this->belongsTo(Category::class , 'cat_id' );
  }

  public function tag()
  {
      return $this->belongsToMany(Tag::class, 'tag_posts');
  }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use App\Models\TagPost;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Posts = Post::all();
        $Content = Post::pluck('content');
        return view('admin.post.index', compact('Posts', 'Content'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Categories = Category::all();
        $Tags = Tag::all();
        return View('admin.post.create' , compact('Categories' , 'Tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([

            'title' => 'required',
            'slug' => 'required',
            'cat_id' => 'required',
            'content' => 'required',
            'tags' => 'required',


        ]);




        if($request->post_id != ''){
            $Post = Post::where('id', $request->post_id)->first();

            $image = $request->file('image');

            if($image){

            $imageName = $image->getClientOriginalName();

            $image->move(public_path('images/post'), $imageName);
           \File::delete(public_path('images/post/'.$Post->image));


            $Post->image = $imageName;
            $Post->title = $request->title;
            $Post->slug = $request->slug;
            $Post->cat_id = $request->cat_id;
          //  $Post->tags = $request->tags;
            $Post->content = $request->content;


            $Post->save();
            $Post->id;

            $TagPost = TagPost::where('post_id', $request->post_id)->delete();
            foreach($request->tags as $item){

                $TagPost = new TagPost();
                $TagPost->tag_id = $item;
                $TagPost->post_id =$Post->id;

                 $TagPost->save();
               }



            return redirect(route('admin.post.index'));
            }
            else{

              
                $Post->title = $request->title;
                $Post->slug = $request->slug;
                $Post->cat_id = $request->cat_id;
              //  $Post->tags = $request->tags;
                $Post->content = $request->content;

                $Post->save();
                $Post->id;

                $TagPost = TagPost::where('post_id', $request->post_id)->delete();
                foreach($request->tags as $item){

                    $TagPost = new TagPost();
                    $TagPost->tag_id = $item;
                    $TagPost->post_id =$Post->id;

                     $TagPost->save();
                   }
                return redirect(route('post'));

            }


           }













        else{



        $Post = new Post();
        $Post->title = $request->title;
        $Post->slug = $request->slug;
        $Post->cat_id = $request->cat_id;
        $Post->content = $request->content;



        if ($request->hasFile('image')) {
            $feature_image = $request->file('image');
            $name = rand(100,10000).'_'.$feature_image->getClientOriginalName();

           // $feature_image->move(public_path('/section-images/home'),$name);
            $feature_image->move(public_path('images/post'), $name);
            $Post->	image = $name;
        }
        $Post->save();
        $Post->id;



         foreach($request->tags as $item){

            $TagPost = new TagPost();
            $TagPost->tag_id = $item;
            $TagPost->post_id =$Post->id;

             $TagPost->save();
           }






    }

       return redirect(route('admin.post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Post = Post::where('id' , $id)->first();
        $TagPost = TagPost::where('post_id', $id)->pluck('tag_id')->toArray();
        $Categories = Category::all();
        $Tags = Tag::all();
        return View('admin.post.create' , compact('Post' , 'Categories','TagPost','Tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Post=Post::where('id', $id)->first();
        \File::delete(public_path('images/post/'.$Post->image));

        $Post=Post::where('id', $id)->delete();
        echo true;

    }
}

resources/views/admin/post/category_popup.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add New Category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">





            <form role="form" id="add_name" method="post" action="{{ route('admin.cat_popup') }}">
                   
                    @csrf



                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="fname">Category Name</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>
                            @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>




                 




        </div>
        <div class="modal-footer">
          <button type="button" id="close" class="btn btn-secondary " data-dismiss="modal">Close</button>
          <button id="submit" type="submit" class="btn btn-primary cat" >Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>





<script>

    $('#submit').click(function(e){
   e.preventDefault();
   /*Ajax Request Header setup*/
 //   alert('hash');
   // var a =  $('#password').val();
   // alert(a);
   $.ajaxSetup({
       headers: {
           "_token": "{{ csrf_token() }}",
       }
   });


   $.ajax({
       url: "{{ route('admin.cat_popup')}}",
       method: 'post',
       data: $('#add_name').serialize(),

       success: function (data) {

       $("#exampleModal #close").click();
       $('#add_name').trigger("reset");
               var s = '<option value="-1"> Select Category</option>';
               for (var i = 0; i < data.length; i++) {
                   s += '<option value="' + data[i].id + '" selected>' + data[i].name + '</option>';

               }
               $("#cat_id").html(s);
           }









    });


       });


</script>

resources/views/admin/post/comments.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->
<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">Comments</h2>
    <div class="separator"></div>


    <table class="table table-bordered data-table" id="comment_table">
        <thead>
            <tr>
                <th>S No.</th>
                <th>Post id</th>
                <th>Comments</th>
                <th>Action</th>

            </tr>
        </thead>
        <tbody>


                @foreach ($PostComment as $post)
                 <tr>
                     <td>{{ $post->id }}</td>
                     <td>{{ $post->post_id  }}</td>
                     <td>{{ $post->comment }}</td>
                     

                     <td>
                         <a href="javascript:" data-id="{{ $post->id }}" class="approve btn btn-success ">Aprrove</a>
                         <a href="javascript:" data-id="{{ $post->id }}" class="delete btn btn-danger ">Delete</a>
                        {{-- <span>
                            <a  href="javascript:" data-id="{{ $post->id }}" class="disapprove btn btn-danger" href="">Dis-Approve</a>
                        </span> --}}
                     </td>


                 </tr>
                @endforeach


                @foreach ($PostCommentApproved as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td>{{ $post->post_id  }}</td>
                    <td>{{ $post->comment }}</td>
                   

                    <td>
                        {{-- <a href="javascript:" data-id="{{ $post->id }}" class="approve btn btn-warning ">Aprrove</a> --}}
                       <span>
                           <a  href="javascript:" data-id="{{ $post->id }}" class="disapprove btn btn-danger" href="">un-Approve</a>

                       </span>
                    </td>


                </tr>
               @endforeach

        </tbody>
    </table>





</div>

<script>
  $(document).ready( function () {
  $(function(){
    $("#comment_table").dataTable();
  });

  });
</script>

<script>
    $(document).on('click', '.check', function(){
       swal("Hello world!");
   });
           $(document).on('click', '.approve', function(){
              var id = $(this).data('id');
           //  alert(id);
              swal({
                  title: "Are you sure?",
                  text: "Comment will Display on The Live Post!",
                  icon: "warning",
                  buttons: true,
                  dangerMode: true,
                  })
                .then((willDelete) => {
                if (willDelete) {
                      var url = "{{ route('admin.ApproveComment',':id') }}";
                      url = url.replace(':id', id);

                      var token = "{{ csrf_token() }}";

                      $.ajax({
                          type: 'GET',
                              url: url,
                              data: {'_token': token, '_method': 'DELETE'},
                              success: function (response) {

                                location.reload();

                          }
                      });

                 }

            });



                   });



                   $(document).on('click', '.disapprove', function(){
              var id = $(this).data('id');
           //  alert(id);
              swal({
                  title: "Are you sure?",
                  text: "Comment will Not Display on The Live Post......!",
                  icon: "warning",
                  buttons: true,
                  dangerMode: true,
                  })
                .then((willDelete) => {
                if (willDelete) {
                      var url = "{{ route('admin.DisApproveComment',':id') }}";
                      url = url.replace(':id', id);

                      var token = "{{ csrf_token() }}";

                      $.ajax({
                          type: 'GET',
                              url: url,
                              data: {'_token': token, '_method': 'DELETE'},
                              success: function (response) {
                              //   alert('Comment Dis-Approved on the post');


                              location.reload();
                           // loadTable();



                          }
                      });

                 }



             });




                   });




                   $(document).on('click', '.delete', function(){
              var id = $(this).data('id');
          //   alert(id);
              swal({
                  title: "Are you sure?",
                  text: "Once deleted, you will not be able to recover data!",
                  icon: "warning",
                  buttons: true,
                  dangerMode: true,
                  })
                .then((willDelete) => {
                if (willDelete) {
                      var url = "{{ route('admin.DelApproveComment',':id') }}";
                      url = url.replace(':id', id);

                      var token = "{{ csrf_token() }}";

                      $.ajax({
                          type: 'GET',
                              url: url,
                              data: {'_token': token, '_method': 'DELETE'},
                              success: function (response) {
                               swal("Poof! Your imaginary file has been deleted!", {
                                      icon: "success",
                                            });
                            location.reload();
                          

                          }
                      });

                 }

                 else {
                        swal("Your imaginary file is safe!");
                      }
            });





                   });







</script>

@endsection

resources/views/admin/post/create.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->

<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
    <!-- WCMS content -->
    <form action="{{route('admin.post.store')}}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="post_id" value="@if(isset($Post)){{$Post->id}} @endif" >
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="fname">Title :</label>
                    <input type="text" class="form-control" id="title" name="title" value="@if(isset($Post)){{$Post->title}} @endif">
                </div>
                @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="fname">Slug :</label>
                    <input type="text" class="form-control" id="slug" name="slug" value="@if(isset($Post)){{$Post->slug}} @endif">
                </div>
                @error('slug')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

        </div>
        @if(isset($Post))
        <div class="row">
            <div class="col-md-6">
                <div class="form-group ">
                    <label for="fname">old Image :</label>
                  <img class=" ml-5" src="{{ asset('images/post/'.$Post->image)}}"  width="250" height="100">
                </div>
                @error('image')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        @endif

        <div class="row">
            <div class="col-md-6">
                <div class="form-group ">
                    <label for="fname">Feature Image :</label>
                   <input type="file" name = "image" class="form-control " value="@if(isset($Post)){{$Post->image}} @endif">
                </div>
                @error('image')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>



        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label for="fname">Category :</label></br>
                    <select class="form-control" type="text" name="cat_id" id="cat_id" >
                       <option value="">Select Category</option>

                     @foreach ($Categories as $cat)
                            {{-- <option value="{{$cat->id}}">{{$cat->name}}</option> --}}
 <option class="option" @if(isset($Post)) @if($Post->cat_id  == $cat->id) selected @endif  @endif value="{{$cat->id}}">{{$cat->name}}</option>
                        @endforeach
                    </select>
                </div>
                    @error('cat_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>


            <div class="col-md-4 mt-2">
               <div class="form-group">
                <label for="fname"></label></br>
                  <a class="btn btn-primary" href="javascript:" class="show " id="cat" data-toggle="modal" data-target="#exampleModal">Add Category</a>
               </div>
            </div>



        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label for="fname">Tags :</label></br>
                    <select class="form-control" type="text" name="tags[]" class="tags" id="tags_id" multiple>

                        @foreach ($Tags as $tag)
                        {{-- <option value="{{$model->name}}">{{$model->name}}</option> --}}

                        <option @if(isset($TagPost)) @if(in_array($tag->id , $TagPost)) selected @endif @endif value="{{$tag->id}}">{{$tag->name}}</option>
                    @endforeach
                    </select>
                </div>
                    @error('tags')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>


            <div class="col-md-4">
                <div class="form-group">
                    <label for="fname"></label></br>
                    {{-- <a type="button" class="btn btn-primary mt-2 text-white" style="float: left;" data-toggle="modal" data-target="TagModal">+ Add Tag</a> --}}
                    <a class="btn btn-primary" href="javascript:" class="show " id="cat" data-toggle="modal" data-target="#TagModal">Add Tag</a>
                </div>

            </div>


        </div>



        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label><strong>Description :</strong></label>
                    <textarea class="form-control" id="editor1" name="content">@if(isset($Post)){{$Post->content}} @endif</textarea>
                </div>

            </div>
        </div>
    <button type="submit" class="mt-5 btn btn-light" style="width: 100%;">Save</button>
    </form>
</div>
@include('admin.post.category_popup')
@include('admin.post.tag_popup')

<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script type="text/javascript">
    CKEDITOR.replace( 'editor1' );
</script>
<script>
    $(document).ready(function(){
   $("#title").on("keyup", function () {
       var Text = $(this).val();
           Text = Text.toLowerCase();
           Text = Text.replace(/[^a-zA-Z0-9]+/g,'-');
      $("#slug").val(Text);
   });


    });
   </script>


@endsection

resources/views/admin/post/index.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->
<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a  style="float: right;" href="{{route('admin.post.create')}}" class="btn btn-light">+ Add New</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">Posts</h2>
    <div class="separator"></div>


<table class="table text-white" id="contact_table">
<thead>
    <tr>
        <th>#</th>
        <th>Title</th>
        <th>Slug</th>
        <th>feature Image</th>
        <th>Category</th>
        <th width="200px">Action</th>
    </tr>
</thead>
<tbody>
    @foreach ($Posts as $post)
    <tr>
        <td>{{ $post->id }}</td>
        <td>{{ $post->title }}</td>
        <td>{{ $post->slug  }}</td>
        {{-- <td>{{ $post->image }}</td> --}}
        <td><img src="{{ asset('images/post/'.$post->image)}}"  width="200" height="100"></td>
        <td>{{ $post->Category->name }}</td>
       
        <td>
           @csrf
           <a class="btn btn-warning" href="{{ route('admin.post.edit',$post->id) }}">Edit</a>
           <a class="btn btn-danger delete" data-id="{{ $post->id }}" href="javascript:">Delete</a>
           {{-- <a href="javascript:" data-id="{{ $post->id }}" class="delete btn btn-danger ">Delete Post</a> --}}
        </td>

    </tr>
    @endforeach

  
</tbody>
</table>

</div>

<script>
  $(document).ready( function () {
  $(function(){
    $("#contact_table").dataTable();
  });

  });
</script>
<script>

    $(document).on('click', '.delete', function(){
               var id = $(this).data('id');
           //   alert(id);
               swal({
                   title: "Are you sure?",
                   text: "Once deleted, you will not be able to recover data!",
                   icon: "warning",
                   buttons: true,
                   dangerMode: true,
                   })
                 .then((willDelete) => {
                 if (willDelete) {
                       var url = "{{route('admin.post.destroy', ':id')}}";
                       url = url.replace(':id', id);

                       var token = "{{ csrf_token() }}";

                       $.ajax({
                           type: 'POST',
                               url: url,
                               data: {'_token': token, '_method': 'DELETE'},
                               success: function (response) {
                               window.location.reload();
                           }
                       });

                  }

                  else {
                         swal("Your imaginary file is safe!");
                       }
             });





                    });

</script>
@endsection

resources/views/admin/post/tag_popup.blade.php
<!-- Modal -->
<div class="modal fade" id="TagModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add New Tag</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">





                <form id="tag_form"  action="{{ route('admin.tag_popup') }}" method="POST" enctype="multipart/form-data">

                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="fname">Tag Name</label>
                                <input type="text" class="form-control"  id="name" name="name" >
                            </div>
                            @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>




                    {{-- <button type="submit" class="btn btn-primary">Submit</button> --}}
                  {{-- </form> --}}






        </div>
        <div class="modal-footer">
          <button type="button" id="close" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="submitTag" type="submit" class="btn btn-primary" >Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>

  <script>

    $('#submitTag').click(function(e){
   e.preventDefault();
   /*Ajax Request Header setup*/
  //  alert('submitTag');
   // var a =  $('#password').val();
   // alert(a);
   $.ajaxSetup({
       headers: {
           "_token": "{{ csrf_token() }}",
       }
   });


   $.ajax({
       url: "{{ route('admin.tag_popup')}}",
       method: 'post',
       data: $('#tag_form').serialize(),

       success: function (data) {
               // console.log(data);
       $("#TagModal #close").click();
       $('#tag_form').trigger("reset");
               var s = '';
               for (var i = 0; i < data.length; i++) {
                   s += '<option value="' + data[i].id + '" >' + data[i].name + '</option>';

               }
               $("#tags_id").html(s);



           }









    });


       });


</script>