routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', [App\Http\Controllers\WcmsController::class, 'index'])->name('index');
Route::get('/about-us', [App\Http\Controllers\WcmsController::class, 'about_us'])->name('about_us');
Route::get('/contact-us', [App\Http\Controllers\WcmsController::class, 'contact_us'])->name('contact_us');
Route::get('/our-services', [App\Http\Controllers\WcmsController::class, 'our_services'])->name('our_services');
Route::get('/our-tour', [App\Http\Controllers\WcmsController::class, 'our_tour'])->name('our_tour');
Route::get('/travel-form', [App\Http\Controllers\WcmsController::class, 'travel_form'])->name('travel_form');
Route::get('get_travel_form', [App\Http\Controllers\WcmsController::class, 'get_travel_form'])->name('get_travel_form');
Route::get('/get-quotes', [App\Http\Controllers\WcmsController::class, 'get_quotes'])->name('get_quotes');

Route::post('/contact_us_store', [App\Http\Controllers\WcmsController::class, 'contact_us_store'])->name('contact_us_store');
Route::post('/quotes_store', [App\Http\Controllers\WcmsController::class, 'quotes_store'])->name('quotes_store');
Route::post('/book_tour', [App\Http\Controllers\WcmsController::class, 'book_tour'])->name('book_tour');

Route::get('post/{id}/{slug}', [App\Http\Controllers\BlogController::class, 'single_post'])->name('single_post');
Route::get('posts_by_category', [App\Http\Controllers\BlogController::class, 'posts_by_category'])->name('posts_by_category');
Route::get('all_post/{cate_id?}', [App\Http\Controllers\BlogController::class, 'all_posts'])->name('all_post');
Route::post('comment_store', [App\Http\Controllers\BlogController::class, 'comment_store'])->name('comment.store');



Route::group( [ 'middleware' => 'auth' , 'prefix' => 'admin','as' => 'admin.'], function(){

    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class, 'index'])->name('dashboard');
   
    Route::get('/about_us', [App\Http\Controllers\Admin\AdminController::class, 'about_us'])->name('about_us');
    Route::get('/contact_us', [App\Http\Controllers\Admin\AdminController::class, 'contact_us'])->name('contact_us');
    Route::get('/our_services', [App\Http\Controllers\Admin\AdminController::class, 'our_services'])->name('our_services');
    Route::get('/our_tour', [App\Http\Controllers\Admin\AdminController::class, 'our_tour'])->name('our_tour');
    Route::get('/get_quotes', [App\Http\Controllers\Admin\AdminController::class, 'get_quotes'])->name('get_quotes');
    Route::get('/travel_form', [App\Http\Controllers\Admin\AdminController::class, 'travel_form'])->name('travel_form');
    Route::post('/store_travel_form', [App\Http\Controllers\Admin\AdminController::class, 'store_travel_form'])->name('store_travel_form');

    Route::post('/slider_images_upload', [App\Http\Controllers\Admin\PageController::class, 'slider_images_upload'])->name('slider_images_upload');
    Route::post('/delete_slider_image', [App\Http\Controllers\Admin\PageController::class, 'delete_slider_image'])->name('delete_slider_image');
    Route::post('/home_store', [App\Http\Controllers\Admin\PageController::class, 'home_store'])->name('home_store');
    Route::post('/about_us_store', [App\Http\Controllers\Admin\PageController::class, 'about_us_store'])->name('about_us_store');
    Route::post('/contact_us_store', [App\Http\Controllers\Admin\PageController::class, 'contact_us_store'])->name('contact_us_store');
    Route::post('/our_services_store', [App\Http\Controllers\Admin\PageController::class, 'our_services_store'])->name('our_services_store');
    Route::post('/our_tour_store', [App\Http\Controllers\Admin\PageController::class, 'our_tour_store'])->name('our_tour_store');

    Route::post('/cat_popup', [App\Http\Controllers\CategoryController::class, 'cat_popup'])->name('cat_popup');
    Route::post('/tag_popup', [App\Http\Controllers\TagController::class, 'tag_popup'])->name('tag_popup');
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    
    Route::get('ApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'ApproveComment'])->name('ApproveComment');
    Route::get('DisApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DisApproveComment'])->name('DisApproveComment');
    Route::get('DelApproveComment/{id}',  [App\Http\Controllers\CommentController::class, 'DelApproveComment'])->name('DelApproveComment');
    Route::resource('comments', CommentController::class);

});
Auth::routes();

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return View('admin.tag.index' , compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([

            'name' => 'required',

        ]);

        if($request->tag_id != ''){
            $Tag = Tag::where('id', $request->tag_id)->first();
            $Tag->name = $request->name;
            $Tag->save();

        }

        else{
        $Tag = new Tag;
        $Tag->name = $request->name;
        $Tag->save();
        }
        return redirect()->route('admin.tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag_edit = Tag::where('id' , $id)->first();
        return View('admin.tag.create' , compact('tag_edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    public function tag_popup(Request $request){
        
        $validated = $request->validate([

            'name' => 'required',

        ]);

        $Tag = new Tag;
        $Tag->name = $request->name;
        $Tag->save();

        $Tags = Tag::all();
        return response()->json($Tags);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Tag = Tag::where('id', $id)->delete();
        return true;
    }
}

resources/views/admin/tag/create.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->

<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
    <!-- WCMS content -->
    <form action="{{route('admin.tag.store')}}" method="POST" enctype="multipart/form-data">
      @csrf
    <h2 class="display-3 text-white">Add New Tag</h2>
    <div class="separator"></div>
    <div class="form-group">
        <h2 class="mb-3 text-white">Name</h2>
        <input type="hidden" name="tag_id" id="tag_id" value="@if(isset($tag_edit)) {{$tag_edit->id}} @endif" >
        <input class="form-control" name="name" id="name" type="text" value="@if(isset($tag_edit)) {{$tag_edit->name}} @endif"  required >
      </div>
        
    <button type="submit" class="mt-5 btn btn-light" style="width: 100%;">Save</button>
    </form>
</div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('layout.admin_app')
@section('content')

<!-- Page content holder -->
<div class="page-content p-5" id="content">
    <!-- Toggle Navbar button -->
    <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i
            class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>
            <a  style="float: right;" href="{{route('admin.tag.create')}}" class="btn btn-light">+ Add New</a>
    <!-- WCMS content -->
    <h2 class="display-3 text-white">Tags</h2>
    <div class="separator"></div>


<table class="table text-white" id="contact_table">
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Action</th>
  </tr>
</thead>
<tbody>
  @foreach ($tags as  $data)
  <tr>
    <th>{{$data->id}}</th>
    <td>{{$data->name}}</td>
    <td>
        <a class="btn btn-warning" href="{{ route('admin.tag.edit',$data->id) }}">Edit</a>
        {{-- <a class="btn btn-danger" href="{{ route('DelCat' ,$cat->id) }}">Delete</a> --}}
        <a href="javascript:" data-id="{{ $data->id }}" class="delete btn btn-danger ">Delete</a>
    </td>
  </tr>
  @endforeach
  
</tbody>
</table>

</div>

<script>
  $(document).ready( function () {
  $(function(){
    $("#contact_table").dataTable();
  });

  });
</script>
<script>

    $(document).on('click', '.delete', function(){
               var id = $(this).data('id');
           //   alert(id);
               swal({
                   title: "Are you sure?",
                   text: "Once deleted, you will not be able to recover data!",
                   icon: "warning",
                   buttons: true,
                   dangerMode: true,
                   })
                 .then((willDelete) => {
                 if (willDelete) {
                       var url = "{{route('admin.tag.destroy', ':id')}}";
                       url = url.replace(':id', id);

                       var token = "{{ csrf_token() }}";

                       $.ajax({
                           type: 'POST',
                               url: url,
                               data: {'_token': token, '_method': 'DELETE'},
                               success: function (response) {
                               window.location.reload();
                           }
                       });

                  }

                  else {
                         swal("Your imaginary file is safe!");
                       }
             });





                    });

</script>
@endsection